name: Contexts
on: [push, pull_request]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_ACTOR}"
      - if: ${{ github.event_name == 'pull_request' }}
        run: echo "${{ github.event.pull_request.title }}"
